'use client';
import '../styles/globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import {ApolloProvider} from '@apollo/client'
import {client} from '@/lib/apollo'

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '---font-poppins'
})

export const metadata: Metadata = {
  title: 'Code Ninja',
  description: 'Generated by create next app',
}

export function ApolloClientProvider({ children }: { children: React.ReactNode }) {
  return (
    <ApolloProvider client={client}>
      {children}
    </ApolloProvider>
  )
}

export default function RootLayout({children,}: {
  children: React.ReactNode
}) 
{
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={poppins.className} suppressHydrationWarning={true}>
        <ApolloClientProvider>
          {children}
        </ApolloClientProvider>
      </body>
    </html>
  )
}
