import '../styles/globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '---font-poppins'
})

export const metadata: Metadata = {
  title: 'Code Ninja',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {
  children: React.ReactNode
}) 
{
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
